### ISSUE TITLE
MQTT Support

### ISSUE THREAD

**Issue by Dotmaster5** [sustainabledeveloper/BS20#17]
Is it Possible to integrate MQTT Support? 

If it is Possible, we can use the Besen BS20 based Wallboxes with evcc for automated pv charging, that would be a whole new level of using this cheap Wallboxes.

**Comment by b2un0** [comment]
you can do this from HA with automations?!

otherwhise try this with bluetooth
https://github.com/slespersen/evseMQTT

**Comment by b2un0** [comment]
you can do this from HA with automations?!

something like this

```yaml
mode: single
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.hms_800_01_inverter_ac_leistung
    for:
      hours: 0
      minutes: 10
      seconds: 0
    above: 400
conditions:
  - condition: state
    entity_id: sensor.bs20_8368555670377598_charger_plug_state
    state: Connected
actions:
  - action: button.press
    metadata: {}
    data: {}
    target:
      entity_id: button.bs20_8368555670377598_start_charging

```

With this EVSE, however, you must keep in mind that you cannot control the charging power dynamically.

It either switches on or off, nothing else.
You have to set the maximum power beforehand

otherwise try this with bluetooth
https://github.com/slespersen/evseMQTT
